// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiHbGggS-i41tFFRT630-8SvBhEn6AiRk',
    appId: '1:156624986105:web:f8ddb2443f937c998ca728',
    messagingSenderId: '156624986105',
    projectId: 'mo-e-learn',
    authDomain: 'mo-e-learn.firebaseapp.com',
    storageBucket: 'mo-e-learn.appspot.com',
    measurementId: 'G-KJJFZTKYL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNEw1TtBARl3XFdEt8p3frZghhpCYlyUo',
    appId: '1:156624986105:android:336871be00d778538ca728',
    messagingSenderId: '156624986105',
    projectId: 'mo-e-learn',
    storageBucket: 'mo-e-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA80crXqbBupVFzMffCz9pzznADzM_HaM0',
    appId: '1:156624986105:ios:c28502ef61568b148ca728',
    messagingSenderId: '156624986105',
    projectId: 'mo-e-learn',
    storageBucket: 'mo-e-learn.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA80crXqbBupVFzMffCz9pzznADzM_HaM0',
    appId: '1:156624986105:ios:796d36e2fca7df488ca728',
    messagingSenderId: '156624986105',
    projectId: 'mo-e-learn',
    storageBucket: 'mo-e-learn.appspot.com',
    iosBundleId: 'com.example.eLearning.RunnerTests',
  );
}
